### ISSUE TITLE
hydra config

### ISSUE THREAD

**Issue by xdcui-nlp** [ZeguanXiao/BERT4GCN_lightning#1]
Hi, I'm very interested in your work, however, I'm not very good at understanding hydra config code, is there a version that doesn't use hydra? I look forward to your reply.

**Comment by ZeguanXiao** [comment]
@xdcui-nlp Sorry, there is not a non-hydra version. If you are umfimiliar with hydra, you can check [the template used by our code](https://github.com/ashleve/lightning-hydra-template) for better understanding.

**Comment by yao92311** [comment]
作者你好，我在尝试运行schedule.sh时解释器报错SyntaxError: invalid syntax
File "train.py", line 11
def main(config: DictConfig):
^
SyntaxError: invalid syntax

我做了以下尝试：
将train.py内main方法做了修改
@hydra.main(config_path="configs/", config_name="train.yaml")
def main():
config=DictConfig
# Imports can be nested inside @hydra.main to optimize tab completion
# https://github.com/facebookresearch/hydra/issues/934
from src import utils
from src.training_pipeline import train

# Applies optional utilities
utils.extras(config)

# Train model
return train(config)
接踵而至的问题是
Traceback (most recent call last):
File "train.py", line 1, in
import dotenv
ImportError: No module named dotenv

但我的python环境下是有python-dotenv包的。遂止步于此，故请教下您。
