### ISSUE TITLE
复现遇到问题了

### ISSUE THREAD

**Issue by yao92311** [ZeguanXiao/BERT4GCN_lightning#2]
你好 我复现时遇到这个问题 In 'train.yaml': Could not find 'model/mnist.yaml'  求指教

**Comment by ZeguanXiao** [comment]
@yao92311 你好，请问你运行代码的命令是什么？可否给出完整的错误提示？

**Comment by yao92311** [comment]
你好 我直接运行了train.py文件  提示在configs文件中的model里面没有mnist.yaml文件  
运行结果如下：
In 'train.yaml': Could not find 'model/mnist.yaml'

Available options in 'model':
	bert4gcn
Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file:///home/wb415/gaq/gvv/configs
	provider=hydra-colorlog, path=pkg://hydra_plugins.hydra_colorlog.conf
	provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by ZeguanXiao** [comment]
@yao92311 你好，请仔细查看README中的指引，查看scripts/schedule.sh脚本中的运行命令。

**Comment by yao92311** [comment]
作者你好，我在尝试运行schedule.sh时解释器报错SyntaxError: invalid syntax
  File "train.py", line 11
    def main(config: DictConfig):
                   ^
SyntaxError: invalid syntax

我做了以下尝试：
将train.py内main方法做了修改
@hydra.main(config_path="configs/", config_name="train.yaml")
def main():
    config=DictConfig
    # Imports can be nested inside @hydra.main to optimize tab completion
    # https://github.com/facebookresearch/hydra/issues/934
    from src import utils
    from src.training_pipeline import train

    # Applies optional utilities
    utils.extras(config)

    # Train model
    return train(config)

接踵而至的问题是
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    import dotenv
ImportError: No module named dotenv

但我的python环境下是有python-dotenv包的。遂止步于此，故请教下您。
