### ISSUE TITLE
问题求解

### ISSUE THREAD

**Issue by yao92311** [ZeguanXiao/BERT4GCN_lightning#3]
作者你好，我在尝试运行schedule.sh时解释器报错SyntaxError: invalid syntax
File "train.py", line 11
def main(config: DictConfig):
^
SyntaxError: invalid syntax

我做了以下尝试：
将train.py内main方法做了修改
@hydra.main(config_path="configs/", config_name="train.yaml")
def main():
config=DictConfig
# Imports can be nested inside @hydra.main to optimize tab completion
# https://github.com/facebookresearch/hydra/issues/934
from src import utils
from src.training_pipeline import train

# Applies optional utilities
utils.extras(config)

# Train model
return train(config)
接踵而至的问题是
Traceback (most recent call last):
File "train.py", line 1, in
import dotenv
ImportError: No module named dotenv

但我的python环境下是有python-dotenv包的。遂止步于此，故请教下您。

**Comment by ZeguanXiao** [comment]
你好，这应该是python路径或者环境相关的问题，可以仔细检查一下
